apiVersion: v1
kind: Namespace
metadata:
  name: loadtest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: loadtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx1
        image: nginx:latest
        ports:
        - containerPort: 80
      - name: nginx2
        image: nginx:latest
        ports:
        - containerPort: 8000
        # resources:
        #   requests:
        #     memory: "1Gi"
        #     cpu: "1"
        #   limits:
        #     memory: "1Gi"
        #     cpu: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadtest
  namespace: loadtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtest
  template:
    metadata:
      labels:
        app: loadtest
    spec:
      containers:
      - name: loadtest-nginx
        image: nginx:latest
      - name: loadtest-busybox
        image: busybox
        command: ["sh", "-c", "while true; do sleep 3600; done"]
---
apiVersion: v1
kind: Pod
metadata:
  name: failing-pod
  namespace: loadtest
spec:
  containers:
  - name: failing-container
    image: busybox
    command: ["sh", "-c", "exit 1"] 
---
apiVersion: v1
kind: Pod
metadata:
  name: failing-pod-1
  namespace: loadtest
spec:
  containers:
  - name: failing-container-1
    image: busybox
    command: ["sh", "-c", "exit 1"] 
---
apiVersion: v1
kind: Pod
metadata:
  name: failing-pod-2
  namespace: loadtest
spec:
  containers:
  - name: failing-container-2
    image: busybox
    command: ["sh", "-c", "exit 1"] 
---
apiVersion: v1
kind: Pod
metadata:
  name: failing-pod-3
  namespace: loadtest
spec:
  containers:
  - name: failing-container-3
    image: busybox
    command: ["sh", "-c", "exit 1"] 
---
apiVersion: v1
kind: Pod
metadata:
  name: failing-pod-4
  namespace: loadtest
spec:
  containers:
  - name: failing-container-4
    image: busybox
    command: ["sh", "-c", "exit 1"] 

   
---
apiVersion: v1
kind: Pod
metadata:
  name: failing-pod-5
  namespace: loadtest
spec:
  containers:
  - name: failing-container-5
    image: busybox
    command: ["sh", "-c", "exit 1"] 

   
---
apiVersion: v1
kind: Pod
metadata:
  name: failing-pod-6
  namespace: loadtest
spec:
  containers:
  - name: failing-container-6
    image: busybox
    command: ["sh", "-c", "exit 1"] 
---
apiVersion: v1
kind: Pod
metadata:
  name: failing-pod-7
  namespace: loadtest
spec:
  containers:
  - name: failing-container-7
    image: busybox
    command: ["sh", "-c", "exit 1"] 
---
apiVersion: v1
kind: Pod
metadata:
  name: failing-pod-8
  namespace: loadtest
spec:
  containers:
  - name: failing-container-8
    image: busybox
    command: ["sh", "-c", "exit 1"]

---
apiVersion: v1
kind: Pod
metadata:
  name: failing-pod-9
  namespace: loadtest
spec:
  containers:
  - name: failing-container-9
    image: busybox
    command: ["sh", "-c", "exit 1"] 


---
apiVersion: v1
kind: Pod
metadata:
  name: failing-pod-10
  namespace: loadtest
spec:
  containers:
  - name: failing-container-10
    image: busybox
    command: ["sh", "-c", "exit 1"] 


---
apiVersion: v1
kind: Pod
metadata:
  name: failing-pod-11
  namespace: loadtest
spec:
  containers:
  - name: failing-container-11
    image: busybox
    command: ["sh", "-c", "exit 1"] 

